# Don't modify this file, it's handle/created by terraform
# check ../script_ansible.tf for more info 
- hosts: localhost
  connection: local
  become: yes
  name: Configuring Local Host

  tasks:
  - name: Install python storm for ~/.ssh/config management
    pip:
      name: stormssh

  
  - name: adding instance dev-1 to ~/.ssh/config
    become_user: augartep92
    community.general.ssh_config:
      user: augartep92
      remote_user: centos
      #remote_user: ubuntu
      host: "dev-1"
      hostname: "54.244.139.232"
      identity_file: "$HOME/.ssh/myKey.pem"
      state: "{{ dev_1_state | default('present') }}"
    when: 
        - dev_1_state is undefined or dev_1_state is defined
        